apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web1-deployment
  labels:
    app : my-k8s1-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      project: myproject-1
  template:
    metadata:
      labels:
        project: myproject-1   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : myproject-1-web
          image: timurit/k8sphp:version1
          ports:
            - containerPort: 80
