apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-replicas
  labels:
    app  : my-k8s-application
    env  : prod
    owner: TimurJafarov
spec:
  replicas: 3
  selector:
    matchLabels:
      project: myproject-2
  template:
    metadata:
      labels:
        project: myproject-2
    spec:
      containers:
        - name : myproject-2-web
          image: timurit/k8sphp:version2
          ports:
            - containerPort: 80
