apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web2-deployment
  labels:
    app : my-k8s2-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      project: myproject-2
  template:
    metadata:
      labels:
        project: myproject-2   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : myproject-2-web
          image: timurit/k8sphp:version2
          ports:
            - containerPort: 80
