apiVersion: v1
kind: Service
metadata:
  name: my-single-pod2-service
  labels:
    env  : prod
    owner: TimurJafarov
spec:
  selector:
    project: myproject-2    # Selecting PODS with those Labels
  ports:
    - name      : app-listener2
      protocol  : TCP
      port      : 80  # Port on Load Balancer
      targetPort: 80  # Port on POD
  type: LoadBalancer
